name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package
          echo "VSIX_PATH=$(find . -maxdepth 1 -name "*.vsix" -type f -printf '%f\n')" >> $GITHUB_ENV
      
      - name: Debug Info
        run: |
          ls -la
          echo "VSIX file: ${{ env.VSIX_PATH }}"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          files: |
            ./*.vsix
            README.md
            CHANGELOG.md
          fail_on_unmatched_files: true
